#!/usr/bin/env python3
"""Generate grammar symbol constants and use them in the handwritten interpreter."""
import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[1]
rules=json.loads((root/'internal/grammar/grammar.json').read_text())
constants={n:'kind'+n for n in rules}
def walk(e):
 yield e
 for a in e.get('args',[]):yield from walk(a)
for r in rules.values():
 for e in walk(r['expr']):
  constants.setdefault(e['op'],'op'+e['op'].capitalize())
  if e['op']=='assign':constants.setdefault(e['text'],'field'+e['text'][0].upper()+e['text'][1:])
for t in ['id','int','string','lit','comment','other','eof','rule','datatype','terminal','enum','true','error','warning','None','String','TEAM','ORGANIZATIONAL','SYSTEM_LANDSCAPE','OHS','CF','ACL','List','Bag','UNDEFINED','ordinal','databaseLength','void','SL_COMMENT','ML_COMMENT','ID','STRING','INT','syntax','limit']:
 constants.setdefault(t,'symbol'+t[0].upper()+t[1:])
# Unique Go identifiers for potentially identical generated names.
used=set()
for value,name in list(constants.items()):
 while name in used:name+='Symbol'
 constants[value]=name;used.add(name)
lines=['// Code generated by scripts/generate_constants.py from pinned grammar symbols; DO NOT EDIT.','','package cmlgo','','const (']
for value,name in sorted(constants.items()):lines.append(' '+name+' = '+json.dumps(value))
lines.append(')\n');(root/'grammar_constants_generated.go').write_text('\n'.join(lines))
string=re.compile(r'`[^`]*`|"(?:\\.|[^"\\])*"')
for p in root.glob('*.go'):
 if p.name.endswith('_generated.go') or p.name.endswith('_test.go'):continue
 def replace(m):
  token=m.group()
  if not token.startswith('"'):return token
  try:value=json.loads(token)
  except json.JSONDecodeError:return token
  return constants.get(value,token)
 p.write_text(string.sub(replace,p.read_text()))
