#!/usr/bin/env python3
"""Generate typed Go objects from the pinned Xtext assignments, not a second schema."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
rules=json.loads((root/'internal/grammar/grammar.json').read_text())
scalar={n for n,r in rules.items() if r['kind']!='rule'}|{'ID','STRING','INT','SL_COMMENT','ML_COMMENT'}
def walk(e):
 yield e
 for a in e.get('args',[]):yield from walk(a)
def fields(n):
 out={}
 for e in walk(rules[n]['expr']):
  if e['op']=='assign':out.setdefault(e['text'],[]).append(e)
 return out
def kinds_expr(e,seen):
 if any(x['op']=='assign' for x in walk(e)):return set()
 if e['op']=='call':return kinds(e['text'],seen)
 out=set()
 for a in e.get('args',[]):out|=kinds_expr(a,seen)
 return out
def kinds(n,seen=None):
 seen=set() if seen is None else seen
 if n in seen or n in scalar or n not in rules:return set()
 seen=seen|{n};out={n} if fields(n) else set()
 e=rules[n]['expr']
 if e['op']=='alt':
  for a in e['args']:out|=kinds_expr(a,seen)
 elif not fields(n):out|=kinds_expr(e,seen)
 return out

def field_type(assignments):
 if any(e['mode']=='?=' for e in assignments):return 'bool'
 ats=[x for e in assignments for x in walk(e['args'][0]) if x['op'] in ['call','ref','lit']]
 refs={x['text'] for x in ats if x['op']=='ref'}
 calls={x['text'] for x in ats if x['op']=='call'}
 if refs:
  if len(refs)>1:
   supers=[n for n in rules if n not in scalar and set().union(*(kinds(r) for r in refs))<=kinds(n)]
   target=min(supers,key=lambda n:len(kinds(n)))
  else:target=next(iter(refs))
  return '*Ref['+target+']'
 if len(calls)==1:
  target=next(iter(calls))
  if target in ['ID','STRING','INT','SL_COMMENT','ML_COMMENT']:return 'string'
  return target if target in scalar else '*'+target
 if calls and all(c not in scalar for c in calls):
  wanted=set().union(*(kinds(c) for c in calls))
  candidates=[n for n in rules if n not in scalar and wanted<=kinds(n)]
  if candidates:return '*'+min(candidates,key=lambda n:len(kinds(n)))
 return 'string'
def go_name(n):
 names={'importURI':'ImportURI','domainVisionStatement':'DomainVisionStatement'}
 return names.get(n,n[0].upper()+n[1:])
lines=['// Code generated by scripts/generate_models.py from CML 6.12.0 and CMLGo extensions; DO NOT EDIT.','','package cmlgo','']
for n,r in rules.items():
 if r['kind']!='rule':
  lines.extend(['// '+n+' представляет скалярное правило CML.','type '+n+' string',''])
  if r['kind']=='enum':
   vals=[]
   for x in walk(r['expr']):
    if x['op']=='lit' and x['text'] not in vals:vals.append(x['text'])
   lines.append('const (')
   for value in vals:
    cname=n+''.join(w[0].upper()+w[1:].lower() for w in value.split('_'))
    lines.append(f' {cname} {n} = {json.dumps(value)}')
   lines.extend([')',''])
  continue
 fs=fields(n)
 variants=sorted(kinds(n)-{n})
 lines.extend(['// '+n+' представляет объект или union исходной грамматики CML.','type '+n+' struct {'])
 for f,assignments in fs.items():
  typ=field_type(assignments)
  if any(e['mode']=='+=' for e in assignments):typ='[]'+typ
  lines.append(f' {go_name(f)} {typ} `json:"{f},omitempty" cml:"{f}"`')
 for variant in variants:lines.append(f' {variant} *{variant} `json:"{variant},omitempty" cmlVariant:"{variant}"`')
 lines.append(' Position Position `json:"-" cml:"-"`')
 lines.append(' Raw *Node `json:"-" cml:"-"`')
 lines.extend(['}','',f'func (*{n}) cmlKind() string {{return "{n}"}}',''])
(root/'models_generated.go').write_text('\n'.join(lines))
print('Generated',len(rules),'types')
